/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projecttenjframe;

import javax.swing.JFrame;

public class Frame extends javax.swing.JFrame {

    int jFrameSekarang;
    
    public Frame(int jFrameSekarang) {
        initComponents();
        this.jFrameSekarang = jFrameSekarang;
        setFrameNumber(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFrameSebelum = new javax.swing.JTextField();
        txtFrameSekarang = new javax.swing.JTextField();
        btnFrameSatu = new javax.swing.JButton();
        btnFrameDua = new javax.swing.JButton();
        btnFrameTiga = new javax.swing.JButton();
        btnFrameEmpat = new javax.swing.JButton();
        btnFrameLima = new javax.swing.JButton();
        btnFrameEnam = new javax.swing.JButton();
        btnFrameTujuh = new javax.swing.JButton();
        btnFrameDelapan = new javax.swing.JButton();
        btnFrameSembilan = new javax.swing.JButton();
        btnFrameSepuluh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jFrame Sebelumnya");

        jLabel2.setText("jFrame Sekarang");

        btnFrameSatu.setText("jFrame 1");
        btnFrameSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameSatuActionPerformed(evt);
            }
        });

        btnFrameDua.setText("jFrame 2");
        btnFrameDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameDuaActionPerformed(evt);
            }
        });

        btnFrameTiga.setText("jFrame 3");
        btnFrameTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameTigaActionPerformed(evt);
            }
        });

        btnFrameEmpat.setText("jFrame 4");
        btnFrameEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameEmpatActionPerformed(evt);
            }
        });

        btnFrameLima.setText("jFrame 5");
        btnFrameLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameLimaActionPerformed(evt);
            }
        });

        btnFrameEnam.setText("jFrame 6");
        btnFrameEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameEnamActionPerformed(evt);
            }
        });

        btnFrameTujuh.setText("jFrame 7");
        btnFrameTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameTujuhActionPerformed(evt);
            }
        });

        btnFrameDelapan.setText("jFrame 8");
        btnFrameDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameDelapanActionPerformed(evt);
            }
        });

        btnFrameSembilan.setText("jFrame 9");
        btnFrameSembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameSembilanActionPerformed(evt);
            }
        });

        btnFrameSepuluh.setText("jFrame 10");
        btnFrameSepuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameSepuluhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrameSatu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameDua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameTiga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameEmpat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameLima))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrameEnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameTujuh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameDelapan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameSembilan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrameSepuluh))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(35, 35, 35)
                            .addComponent(txtFrameSekarang))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtFrameSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFrameSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFrameSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrameSatu)
                    .addComponent(btnFrameDua)
                    .addComponent(btnFrameTiga)
                    .addComponent(btnFrameEmpat)
                    .addComponent(btnFrameLima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrameEnam)
                    .addComponent(btnFrameTujuh)
                    .addComponent(btnFrameDelapan)
                    .addComponent(btnFrameSembilan)
                    .addComponent(btnFrameSepuluh))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void btnFrameSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameSatuActionPerformed
        // TODO add your handling code here: 
//        this.dispose();
//        FrameSatu frameSatu = new FrameSatu();
//        frameSatu.setFrameNumber(jFrameSekarang);
//        frameSatu.setVisible(true);
        changeFrame(new FrameSatu());
    }//GEN-LAST:event_btnFrameSatuActionPerformed

    public void btnFrameDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameDuaActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameDua frameDua = new FrameDua();
//        frameDua.setFrameNumber(jFrameSekarang);
//        frameDua.setVisible(true);
        changeFrame(new FrameDua());
    }//GEN-LAST:event_btnFrameDuaActionPerformed

    public void btnFrameTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameTigaActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameTiga frameTiga = new FrameTiga();
//        frameTiga.setFrameNumber(jFrameSekarang);
//        frameTiga.setVisible(true);
        changeFrame(new FrameTiga());
    }//GEN-LAST:event_btnFrameTigaActionPerformed

    public void btnFrameEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameEmpatActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameEmpat frameEmpat = new FrameEmpat();
//        frameEmpat.setFrameNumber(jFrameSekarang);
//        frameEmpat.setVisible(true);
        changeFrame(new FrameEmpat());
    }//GEN-LAST:event_btnFrameEmpatActionPerformed

    public void btnFrameLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameLimaActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameLima frameLima = new FrameLima();
//        frameLima.setFrameNumber(jFrameSekarang);
//        frameLima.setVisible(true);
        changeFrame(new FrameLima());
    }//GEN-LAST:event_btnFrameLimaActionPerformed

    public void btnFrameEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameEnamActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameEnam frameEnam = new FrameEnam();
//        frameEnam.setFrameNumber(jFrameSekarang);
//        frameEnam.setVisible(true);
        changeFrame(new FrameEnam());
    }//GEN-LAST:event_btnFrameEnamActionPerformed

    public void btnFrameTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameTujuhActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameTujuh frameTujuh = new FrameTujuh();
//        frameTujuh.setFrameNumber(jFrameSekarang);
//        frameTujuh.setVisible(true);
        changeFrame(new FrameTujuh());
    }//GEN-LAST:event_btnFrameTujuhActionPerformed

    public void btnFrameDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameDelapanActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameDelapan frameDelapan = new FrameDelapan();
//        frameDelapan.setFrameNumber(jFrameSekarang);
//        frameDelapan.setVisible(true);
        changeFrame(new FrameDelapan());
    }//GEN-LAST:event_btnFrameDelapanActionPerformed

    public void btnFrameSembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameSembilanActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameSembilan frameSembilan = new FrameSembilan();
//        frameSembilan.setFrameNumber(jFrameSekarang);
//        frameSembilan.setVisible(true);
        changeFrame(new FrameSembilan());
    }//GEN-LAST:event_btnFrameSembilanActionPerformed

    public void btnFrameSepuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameSepuluhActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        FrameSepuluh frameSepuluh = new FrameSepuluh();
//        frameSepuluh.setFrameNumber(jFrameSekarang);
//        frameSepuluh.setVisible(true);
        changeFrame(new FrameSepuluh());
    }//GEN-LAST:event_btnFrameSepuluhActionPerformed
    
    public void setFrameNumber(int jFrameSebelum) {
        txtFrameSebelum.setText("" + jFrameSebelum);
        txtFrameSekarang.setText("" + jFrameSekarang);
    }
    
    public void changeFrame(Frame newFrame) {
        this.dispose();
        newFrame.setFrameNumber(jFrameSekarang);
        newFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnFrameDelapan;
    public javax.swing.JButton btnFrameDua;
    public javax.swing.JButton btnFrameEmpat;
    public javax.swing.JButton btnFrameEnam;
    public javax.swing.JButton btnFrameLima;
    public javax.swing.JButton btnFrameSatu;
    public javax.swing.JButton btnFrameSembilan;
    public javax.swing.JButton btnFrameSepuluh;
    public javax.swing.JButton btnFrameTiga;
    public javax.swing.JButton btnFrameTujuh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFrameSebelum;
    private javax.swing.JTextField txtFrameSekarang;
    // End of variables declaration//GEN-END:variables
}
